import "../styles/globals.css";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { LoginProvider } from "../contexts/LoginContext";

function MyApp({ Component, pageProps }) {
  return (
    <>
   
      <Head>
        <title>Warranty NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/warranty.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify justify-between">
        <LoginProvider>
          <div className="bg-gradient-to-r from-yellow-500 to-slate-500 opacity-4 bg-transparent">
            <Navbar />
          </div>
          <Component {...pageProps} />
          <div className="bg-gradient-to-r from-slate-500 to-gray-400 opacity-4 bg-transparent mt-20">
            <Footer />
          </div>
        </LoginProvider>
      </div>
    </>
  );
}

export default MyApp;
